version: '0.1'

services:
  api:
    image: fulltimeforce-be
    container_name: fulltimeforce-be-api
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env 

  postgres:
    image: postgres:10.4-alpine
    container_name: fulltimeforce-be-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: fulltimeforce-be-pgadmin
    ports:
      - '8888:80'
    volumes:
      - admin_data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db_data:
  admin_data: